######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 31 17:34:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h main.h menu1.h menu2.h menu3.h
SOURCES += main.cpp menu1.cpp menu2.cpp menu3.cpp
