######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 29 10:55:30 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
