######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 20 19:49:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h textWindow.h
SOURCES += main.cpp mainWindow.cpp textWindow.cpp
