######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 14:57:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h node.h
SOURCES += main.cpp node.cpp
